repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    -   id: black
        language_version: python3.9
